-- Migration: create classes table
-- Run in Supabase SQL Editor

create table if not exists public.classes (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    teacher_unique_id text not null,
    class_name text not null,
    duration_minutes integer not null check (duration_minutes > 0),
    class_time time without time zone not null,
    class_start_at timestamptz not null,
    class_end_at timestamptz not null,
    notification_status text not null default 'pending',
    notification_scheduled_for timestamptz,
    notification_sent_at timestamptz,
    attendance_notification_status text not null default 'pending',
    attendance_notification_sent_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists classes_teacher_unique_id_idx
    on public.classes (teacher_unique_id);

create index if not exists classes_created_at_idx
    on public.classes (created_at desc);

create index if not exists classes_start_end_idx
    on public.classes (class_start_at, class_end_at);
