create table if not exists public.teachers (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    teacher_id text not null,
    password text not null,
    created_at timestamptz not null default now()
);

create unique index if not exists teachers_teacher_id_key
    on public.teachers (teacher_id);

insert into public.teachers (teacher_name, teacher_id, password)
values
    ('Prof. Priyanka Sinha', 'IOT-PS-06', 'IOT-PS-06'),
    ('Prof. Vivek Sharar', 'IOT-VS-06', 'IOT-VS-06'),
    ('Prof. Dhruv Kumar', 'IOT-DK-06', 'IOT-DK-06'),
    ('Prof. Abhishek Kumar', 'IOT-AK-06', 'IOT-AK-06'),
    ('Prof. Nityanand Kumar', 'IOT-NN-06', 'IOT-NN-06'),
    ('Prof. Nishant Kumar', 'IOT-NK-06', 'IOT-NK-06')
on conflict (teacher_id) do update
set
    teacher_name = excluded.teacher_name,
    password = excluded.password;

alter table public.classes
    drop constraint if exists classes_teacher_unique_id_fkey;
alter table public.classes
    add constraint classes_teacher_unique_id_fkey
    foreign key (teacher_unique_id)
    references public.teachers (teacher_id)
    on update cascade
    on delete restrict;
