-- Supabase full setup for attendance_system.py
-- Paste this entire script into Supabase SQL Editor and run once.

-- 1) Students table
create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_id integer not null,
    name text not null,
    reg_number text not null,
    photo_dir text,
    profile_photo_path text,
    profile_photo_url text,
    registered_date timestamptz default now()
);

alter table public.students add column if not exists photo_dir text;
alter table public.students add column if not exists profile_photo_path text;
alter table public.students add column if not exists profile_photo_url text;
alter table public.students add column if not exists registered_date timestamptz default now();

create unique index if not exists students_reg_number_key
    on public.students (reg_number);

create unique index if not exists students_student_id_key
    on public.students (student_id);

-- 2) Attendance table
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    attendance_date date not null,
    reg_number text not null,
    name text not null,
    time time without time zone not null,
    status text not null default 'Present',
    marked_at timestamptz default now()
);

create unique index if not exists attendance_date_reg_number_key
    on public.attendance (attendance_date, reg_number);

create index if not exists attendance_reg_number_idx
    on public.attendance (reg_number);

-- 3) Student photos metadata table
create table if not exists public.student_photos (
    id bigint generated by default as identity primary key,
    reg_number text not null,
    student_name text not null,
    photo_no integer not null,
    storage_path text not null,
    photo_url text,
    captured_at timestamptz default now()
);

create unique index if not exists student_photos_storage_path_key
    on public.student_photos (storage_path);

create index if not exists student_photos_reg_number_idx
    on public.student_photos (reg_number);

-- 4) Foreign keys
do $$
begin
    if not exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'attendance'
          and constraint_name = 'attendance_reg_number_fkey'
    ) then
        alter table public.attendance
        add constraint attendance_reg_number_fkey
        foreign key (reg_number)
        references public.students (reg_number)
        on update cascade
        on delete restrict;
    end if;

    if not exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'student_photos'
          and constraint_name = 'student_photos_reg_number_fkey'
    ) then
        alter table public.student_photos
        add constraint student_photos_reg_number_fkey
        foreign key (reg_number)
        references public.students (reg_number)
        on update cascade
        on delete cascade;
    end if;
end
$$;

-- 9) Teacher auth setup (safe for older DBs)
create table if not exists public.teachers (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    teacher_id text not null,
    password text not null,
    created_at timestamptz not null default now()
);

create unique index if not exists teachers_teacher_id_key
    on public.teachers (teacher_id);

create table if not exists public.teacher_timetable (
    id bigint generated by default as identity primary key,
    teacher_id text not null,
    day_of_week text not null,
    start_time time without time zone not null,
    end_time time without time zone not null,
    course_code text not null,
    course_title text not null,
    created_at timestamptz not null default now()
);

create index if not exists teacher_timetable_teacher_day_idx
    on public.teacher_timetable (teacher_id, day_of_week, start_time);

create unique index if not exists teacher_timetable_unique_slot
    on public.teacher_timetable (teacher_id, day_of_week, start_time, end_time, course_code);

insert into public.teachers (teacher_name, teacher_id, password)
values
    ('Prof. Priyanka Sinha', 'IOT-PS-06', 'IOT-PS-06'),
    ('Prof. Vivek Sharar', 'IOT-VS-06', 'IOT-VS-06'),
    ('Prof. Dhruv Kumar', 'IOT-DK-06', 'IOT-DK-06'),
    ('Prof. Abhishek Kumar', 'IOT-AK-06', 'IOT-AK-06'),
    ('Prof. Nityanand Kumar', 'IOT-NN-06', 'IOT-NN-06'),
    ('Prof. Nishant Kumar', 'IOT-NK-06', 'IOT-NK-06')
on conflict (teacher_id) do update
set
    teacher_name = excluded.teacher_name,
    password = excluded.password;

insert into public.teacher_timetable (teacher_id, day_of_week, start_time, end_time, course_code, course_title)
values
    ('IOT-PS-06', 'MON', '16:00', '17:00', 'PP', 'Python Programming'),
    ('IOT-PS-06', 'TUES', '12:00', '13:00', 'PP', 'Python Programming'),
    ('IOT-PS-06', 'SAT', '11:00', '12:00', 'PP', 'Python Programming'),

    ('IOT-VS-06', 'FRI', '16:00', '17:00', 'AI&E', 'AI and Ethics'),

    ('IOT-DK-06', 'TUES', '16:00', '17:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'WED', '14:00', '15:00', 'ITI', 'Introduction to Industry 4.0'),
    ('IOT-DK-06', 'THUR', '14:00', '15:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'THUR', '16:00', '17:00', 'ITI', 'Introduction to Industry 4.0'),
    ('IOT-DK-06', 'FRI', '10:00', '11:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'FRI', '12:00', '13:00', 'ITI', 'Introduction to Industry 4.0'),

    ('IOT-AK-06', 'THUR', '10:00', '11:00', 'AHSN', 'Ad hoc Sensor Networks'),
    ('IOT-AK-06', 'THUR', '11:00', '13:00', 'AHSN-Lab', 'Ad hoc Sensor Networks Lab'),
    ('IOT-AK-06', 'FRI', '11:00', '12:00', 'AHSN', 'Ad hoc Sensor Networks'),
    ('IOT-AK-06', 'FRI', '14:00', '16:00', 'AHSN-Lab', 'Ad hoc Sensor Networks Lab'),
    ('IOT-AK-06', 'SAT', '10:00', '11:00', 'AHSN', 'Ad hoc Sensor Networks'),

    ('IOT-NN-06', 'MON', '11:00', '12:00', 'CN', 'Computer Networks'),
    ('IOT-NN-06', 'TUES', '10:00', '11:00', 'CN', 'Computer Networks'),
    ('IOT-NN-06', 'WED', '10:00', '11:00', 'CN', 'Computer Networks'),

    ('IOT-NK-06', 'MON', '12:00', '13:00', 'ML', 'Machine Learning'),
    ('IOT-NK-06', 'TUES', '11:00', '12:00', 'ML', 'Machine Learning'),
    ('IOT-NK-06', 'TUES', '14:00', '16:00', 'ML-Lab', 'Machine Learning Lab'),
    ('IOT-NK-06', 'WED', '11:00', '13:00', 'ML-Lab', 'Machine Learning Lab'),
    ('IOT-NK-06', 'WED', '16:00', '17:00', 'ML', 'Machine Learning')
on conflict (teacher_id, day_of_week, start_time, end_time, course_code) do update
set
    course_title = excluded.course_title;

do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'public'
          and table_name = 'classes'
    ) then
        update public.classes c
        set
            teacher_unique_id = t.teacher_id,
            teacher_name = t.teacher_name
        from public.teachers t
        where lower(trim(c.teacher_name)) = lower(trim(t.teacher_name))
          and c.teacher_unique_id <> t.teacher_id;

        delete from public.classes c
        where not exists (
            select 1
            from public.teachers t
            where t.teacher_id = c.teacher_unique_id
        );

        alter table public.classes
            drop constraint if exists classes_teacher_unique_id_fkey;

        alter table public.classes
            add constraint classes_teacher_unique_id_fkey
            foreign key (teacher_unique_id)
            references public.teachers (teacher_id)
            on update cascade
            on delete restrict;
    end if;
end
$$;

alter table public.teacher_timetable
    drop constraint if exists teacher_timetable_teacher_id_fkey;
alter table public.teacher_timetable
    add constraint teacher_timetable_teacher_id_fkey
    foreign key (teacher_id)
    references public.teachers (teacher_id)
    on update cascade
    on delete cascade;

-- 5) Storage bucket for images (student-photos)
insert into storage.buckets (id, name, public)
values ('student-photos', 'student-photos', true)
on conflict (id) do nothing;

-- 6) Enable RLS
alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.student_photos enable row level security;

-- 7) Table policies (open for anon/authenticated; adjust for production)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'students' and policyname = 'students_all_access'
    ) then
        create policy students_all_access on public.students
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'attendance' and policyname = 'attendance_all_access'
    ) then
        create policy attendance_all_access on public.attendance
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'student_photos' and policyname = 'student_photos_all_access'
    ) then
        create policy student_photos_all_access on public.student_photos
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;
end
$$;

-- 8) Storage object policies for student-photos bucket
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_public_read'
    ) then
        create policy student_photos_public_read
        on storage.objects
        for select
        to public
        using (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_upload'
    ) then
        create policy student_photos_upload
        on storage.objects
        for insert
        to anon, authenticated
        with check (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_update'
    ) then
        create policy student_photos_update
        on storage.objects
        for update
        to anon, authenticated
        using (bucket_id = 'student-photos')
        with check (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_delete'
    ) then
        create policy student_photos_delete
        on storage.objects
        for delete
        to anon, authenticated
        using (bucket_id = 'student-photos');
    end if;
end
$$;
