-- Supabase full setup for attendance_system.py
-- Paste this entire script into Supabase SQL Editor and run once.

-- 1) Students table
create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_id integer not null,
    name text not null,
    reg_number text not null,
    photo_dir text,
    profile_photo_path text,
    profile_photo_url text,
    registered_date timestamptz default now()
);

alter table public.students add column if not exists photo_dir text;
alter table public.students add column if not exists profile_photo_path text;
alter table public.students add column if not exists profile_photo_url text;
alter table public.students add column if not exists registered_date timestamptz default now();

create unique index if not exists students_reg_number_key
    on public.students (reg_number);

create unique index if not exists students_student_id_key
    on public.students (student_id);

-- 2) Attendance table
create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    attendance_date date not null,
    reg_number text not null,
    name text not null,
    time time without time zone not null,
    status text not null default 'Present',
    marked_at timestamptz default now()
);

create unique index if not exists attendance_date_reg_number_key
    on public.attendance (attendance_date, reg_number);

create index if not exists attendance_reg_number_idx
    on public.attendance (reg_number);

-- 3) Student photos metadata table
create table if not exists public.student_photos (
    id bigint generated by default as identity primary key,
    reg_number text not null,
    student_name text not null,
    photo_no integer not null,
    storage_path text not null,
    photo_url text,
    captured_at timestamptz default now()
);

create unique index if not exists student_photos_storage_path_key
    on public.student_photos (storage_path);

create index if not exists student_photos_reg_number_idx
    on public.student_photos (reg_number);

-- 4) Foreign keys
do $$
begin
    if not exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'attendance'
          and constraint_name = 'attendance_reg_number_fkey'
    ) then
        alter table public.attendance
        add constraint attendance_reg_number_fkey
        foreign key (reg_number)
        references public.students (reg_number)
        on update cascade
        on delete restrict;
    end if;

    if not exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'student_photos'
          and constraint_name = 'student_photos_reg_number_fkey'
    ) then
        alter table public.student_photos
        add constraint student_photos_reg_number_fkey
        foreign key (reg_number)
        references public.students (reg_number)
        on update cascade
        on delete cascade;
    end if;
end
$$;

-- 5) Storage bucket for images (student-photos)
insert into storage.buckets (id, name, public)
values ('student-photos', 'student-photos', true)
on conflict (id) do nothing;

-- 6) Enable RLS
alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.student_photos enable row level security;

-- 7) Table policies (open for anon/authenticated; adjust for production)
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'students' and policyname = 'students_all_access'
    ) then
        create policy students_all_access on public.students
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'attendance' and policyname = 'attendance_all_access'
    ) then
        create policy attendance_all_access on public.attendance
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'student_photos' and policyname = 'student_photos_all_access'
    ) then
        create policy student_photos_all_access on public.student_photos
        for all to anon, authenticated
        using (true)
        with check (true);
    end if;
end
$$;

-- 8) Storage object policies for student-photos bucket
do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_public_read'
    ) then
        create policy student_photos_public_read
        on storage.objects
        for select
        to public
        using (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_upload'
    ) then
        create policy student_photos_upload
        on storage.objects
        for insert
        to anon, authenticated
        with check (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_update'
    ) then
        create policy student_photos_update
        on storage.objects
        for update
        to anon, authenticated
        using (bucket_id = 'student-photos')
        with check (bucket_id = 'student-photos');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage'
          and tablename = 'objects'
          and policyname = 'student_photos_delete'
    ) then
        create policy student_photos_delete
        on storage.objects
        for delete
        to anon, authenticated
        using (bucket_id = 'student-photos');
    end if;
end
$$;

