-- Current Supabase schema reference
-- Source: user-provided DB diagram (kept as editable code for future changes)

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_id integer not null,
    name text not null,
    reg_number text not null,
    telegram_id text not null,
    photo_dir text,
    registered_date timestamptz default now(),
    profile_photo_path text,
    profile_photo_url text,
    model_trained boolean not null default false,
    model_trained_at timestamptz
);

create unique index if not exists students_student_id_key
    on public.students (student_id);

create unique index if not exists students_reg_number_key
    on public.students (reg_number);

create table if not exists public.classes (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    teacher_unique_id text not null,
    class_name text not null,
    duration_minutes integer not null,
    class_time time without time zone not null,
    class_start_at timestamptz not null,
    class_end_at timestamptz not null,
    notification_status text not null default 'pending',
    notification_scheduled_for timestamptz,
    notification_sent_at timestamptz,
    attendance_notification_status text not null default 'pending',
    attendance_notification_sent_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists classes_teacher_unique_id_idx
    on public.classes (teacher_unique_id);

create index if not exists classes_created_at_idx
    on public.classes (created_at desc);

create index if not exists classes_start_end_idx
    on public.classes (class_start_at, class_end_at);

create table if not exists public.attendance (
    id bigint generated by default as identity primary key,
    class_id bigint,
    attendance_date date not null,
    reg_number text not null,
    name text not null,
    time time without time zone not null,
    status text not null default 'Present',
    marked_at timestamptz default now()
);

create index if not exists attendance_reg_number_idx
    on public.attendance (reg_number);

create unique index if not exists attendance_class_reg_key
    on public.attendance (class_id, reg_number);

create index if not exists attendance_class_id_idx
    on public.attendance (class_id);

create table if not exists public.student_photos (
    id bigint generated by default as identity primary key,
    reg_number text not null,
    student_name text not null,
    photo_no integer not null,
    storage_path text not null,
    photo_url text,
    captured_at timestamptz default now()
);

create unique index if not exists student_photos_storage_path_key
    on public.student_photos (storage_path);

create index if not exists student_photos_reg_number_idx
    on public.student_photos (reg_number);

alter table public.attendance
    drop constraint if exists attendance_reg_number_fkey;
alter table public.attendance
    add constraint attendance_reg_number_fkey
    foreign key (reg_number)
    references public.students (reg_number)
    on update cascade
    on delete restrict;

alter table public.attendance
    drop constraint if exists attendance_class_id_fkey;
alter table public.attendance
    add constraint attendance_class_id_fkey
    foreign key (class_id)
    references public.classes (id)
    on update cascade
    on delete set null;

alter table public.student_photos
    drop constraint if exists student_photos_reg_number_fkey;
alter table public.student_photos
    add constraint student_photos_reg_number_fkey
    foreign key (reg_number)
    references public.students (reg_number)
    on update cascade
    on delete cascade;
