-- Run this in your SQL database
create table if not exists public.teachers (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    teacher_id text not null,
    password text not null,
    created_at timestamptz not null default now()
);

create unique index if not exists teachers_teacher_id_key
    on public.teachers (teacher_id);

create table if not exists public.teacher_timetable (
    id bigint generated by default as identity primary key,
    teacher_id text not null,
    day_of_week text not null,
    start_time time without time zone not null,
    end_time time without time zone not null,
    course_code text not null,
    course_title text not null,
    created_at timestamptz not null default now()
);

create index if not exists teacher_timetable_teacher_day_idx
    on public.teacher_timetable (teacher_id, day_of_week, start_time);

create unique index if not exists teacher_timetable_unique_slot
    on public.teacher_timetable (teacher_id, day_of_week, start_time, end_time, course_code);

insert into public.teachers (teacher_name, teacher_id, password)
values
    ('Prof. Priyanka Sinha', 'IOT-PS-06', 'IOT-PS-06'),
    ('Prof. Vivek Sharar', 'IOT-VS-06', 'IOT-VS-06'),
    ('Prof. Dhruv Kumar', 'IOT-DK-06', 'IOT-DK-06'),
    ('Prof. Abhishek Kumar', 'IOT-AK-06', 'IOT-AK-06'),
    ('Prof. Nityanand Kumar', 'IOT-NN-06', 'IOT-NN-06'),
    ('Prof. Nishant Kumar', 'IOT-NK-06', 'IOT-NK-06')
on conflict (teacher_id) do update
set
    teacher_name = excluded.teacher_name,
    password = excluded.password;

insert into public.teacher_timetable (teacher_id, day_of_week, start_time, end_time, course_code, course_title)
values
    ('IOT-PS-06', 'MON', '16:00', '17:00', 'PP', 'Python Programming'),
    ('IOT-PS-06', 'TUES', '12:00', '13:00', 'PP', 'Python Programming'),
    ('IOT-PS-06', 'SAT', '11:00', '12:00', 'PP', 'Python Programming'),

    ('IOT-VS-06', 'FRI', '16:00', '17:00', 'AI&E', 'AI and Ethics'),

    ('IOT-DK-06', 'TUES', '16:00', '17:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'WED', '14:00', '15:00', 'ITI', 'Introduction to Industry 4.0'),
    ('IOT-DK-06', 'THUR', '14:00', '15:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'THUR', '16:00', '17:00', 'ITI', 'Introduction to Industry 4.0'),
    ('IOT-DK-06', 'FRI', '10:00', '11:00', 'COI', 'Constitution of India'),
    ('IOT-DK-06', 'FRI', '12:00', '13:00', 'ITI', 'Introduction to Industry 4.0'),

    ('IOT-AK-06', 'THUR', '10:00', '11:00', 'AHSN', 'Ad hoc Sensor Networks'),
    ('IOT-AK-06', 'THUR', '11:00', '13:00', 'AHSN-Lab', 'Ad hoc Sensor Networks Lab'),
    ('IOT-AK-06', 'FRI', '11:00', '12:00', 'AHSN', 'Ad hoc Sensor Networks'),
    ('IOT-AK-06', 'FRI', '14:00', '16:00', 'AHSN-Lab', 'Ad hoc Sensor Networks Lab'),
    ('IOT-AK-06', 'SAT', '10:00', '11:00', 'AHSN', 'Ad hoc Sensor Networks'),

    ('IOT-NN-06', 'MON', '11:00', '12:00', 'CN', 'Computer Networks'),
    ('IOT-NN-06', 'TUES', '10:00', '11:00', 'CN', 'Computer Networks'),
    ('IOT-NN-06', 'WED', '10:00', '11:00', 'CN', 'Computer Networks'),

    ('IOT-NK-06', 'MON', '12:00', '13:00', 'ML', 'Machine Learning'),
    ('IOT-NK-06', 'TUES', '11:00', '12:00', 'ML', 'Machine Learning'),
    ('IOT-NK-06', 'TUES', '14:00', '16:00', 'ML-Lab', 'Machine Learning Lab'),
    ('IOT-NK-06', 'WED', '11:00', '13:00', 'ML-Lab', 'Machine Learning Lab'),
    ('IOT-NK-06', 'WED', '16:00', '17:00', 'ML', 'Machine Learning')
on conflict (teacher_id, day_of_week, start_time, end_time, course_code) do update
set
    course_title = excluded.course_title;

-- Safety migration for old classes data:
-- 1) If teacher name matches, normalize old teacher_unique_id to canonical teacher_id.
update public.classes c
set
    teacher_unique_id = t.teacher_id,
    teacher_name = t.teacher_name
from public.teachers t
where lower(trim(c.teacher_name)) = lower(trim(t.teacher_name))
  and c.teacher_unique_id <> t.teacher_id;

-- 2) Remove legacy class rows that still have unknown teacher ids.
-- This enforces your rule: only timetable teachers can take classes.
delete from public.classes c
where not exists (
    select 1
    from public.teachers t
    where t.teacher_id = c.teacher_unique_id
);

alter table public.classes
    drop constraint if exists classes_teacher_unique_id_fkey;

alter table public.classes
    add constraint classes_teacher_unique_id_fkey
    foreign key (teacher_unique_id)
    references public.teachers (teacher_id)
    on update cascade
    on delete restrict;

alter table public.teacher_timetable
    drop constraint if exists teacher_timetable_teacher_id_fkey;
alter table public.teacher_timetable
    add constraint teacher_timetable_teacher_id_fkey
    foreign key (teacher_id)
    references public.teachers (teacher_id)
    on update cascade
    on delete cascade;

select teacher_name, teacher_id, password from public.teachers order by teacher_name;
select teacher_id, day_of_week, start_time, end_time, course_code, course_title
from public.teacher_timetable
order by teacher_id, day_of_week, start_time;
